monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: grouped
            excluded_http_codes: [503,404]

        grouped:
            type: group
            members: [nested, deduplicated]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        deduplicated:
            type:    deduplication
            handler: swift
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        swift:
            type:       swift_mailer
            from_email: 'contact@ferenost.fr'
            to_email:   ['simon.heban@ferenost.fr','royalguard.62@gmail.com']
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject:    "Une erreur s'est produite! %%message%%"
            level: debug
            formatter:  monolog.formatter.html
            content_type: text/html
